### ISSUE TITLE
bungeecord载入插件报错

### ISSUE THREAD

**Issue by Yuii-guoguo** [TurnALive/Phenyl#1]
17:01:58 [警告] Error loading plugin Phenyl
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
    at live.turna.phenyl.Phenyl.<init>(Phenyl.java:23)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 11 more

**Comment by xslingcn** [comment]
Bungeecord没有使用Log4j2作为日志记录器。从1.1.5开始，Phenyl将在必要的时候自行下载并加载Log4j2，请下载最新发布版本尝试。
