### ISSUE TITLE
Waterfall#496载入报错

### ISSUE THREAD

**Issue by ABCDCreeper** [TurnALive/Phenyl#4]
[21:44:19 INFO]: Using standard Java JCE cipher.
[21:44:19 INFO]: Using standard Java compressor.
[21:44:19 INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496
[21:44:19 INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
[21:44:19 INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
[21:44:19 INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
[21:44:19 INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
[21:44:19 INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
[21:44:19 INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
[21:44:19 INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 ERROR] [Phenyl]: Failed creating library directory
[21:44:19 INFO]: Loaded plugin Phenyl version 1.1.12 by TurnALive
[21:44:19 INFO]: Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Loaded plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Loaded plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 WARN]: Forced host server pvp is not defined
[21:44:19 INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Enabled plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 WARN] [Phenyl]: Main - Missing translation key "logFileFail" in translation file en
[21:44:19 WARN]: Exception encountered when loading plugin: Phenyl
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key logFileFail
        at java.util.ResourceBundle.getObject(ResourceBundle.java:564) ~[?:?]
        at java.util.ResourceBundle.getObject(ResourceBundle.java:558) ~[?:?]
        at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
        at live.turna.phenyl.common.message.I18n.translate(I18n.java:117) ~[?:?]
        at live.turna.phenyl.common.message.I18n.i18n(I18n.java:72) ~[?:?]
        at live.turna.phenyl.common.logger.Logging.setFileLog(Logging.java:60) ~[?:?]
        at live.turna.phenyl.common.logger.Logging.onEnable(Logging.java:94) ~[?:?]
        at live.turna.phenyl.common.plugin.AbstractPhenyl.enable(AbstractPhenyl.java:49) ~[?:?]
        at live.turna.phenyl.bungee.BungeePhenyl.onEnable(BungeePhenyl.java:45) ~[?:?]
        at live.turna.phenyl.bungee.loader.PhenylBungeeLoader.onEnable(PhenylBungeeLoader.java:16) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
[21:44:19 INFO]: Enabled plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Enabled plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:19 INFO]: Enabled plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:ab3ccb8:496 by WaterfallMC
[21:44:20 INFO]: Listening on /0.0.0.0:25565

**Comment by xslingcn** [comment]
请确认插件目录可读写。

**Comment by ABCDCreeper** [comment]
插件目录可读写，sudo也没用

**Comment by ABCDCreeper** [comment]
测试了2遍，在两台机器上，最新的1.1.12不能正常使用，但是1.1.11可以正常使用

**Comment by ABCDCreeper** [comment]
额，新的问题
[11:04:53 ERROR]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[11:04:53 ERROR]:       at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)
[11:04:53 ERROR]:       at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:123)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[11:04:53 ERROR]:       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.utils.crypto.ECDHKt.getDefaultInitialPublicKey(ECDH.kt:132)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.AccountSecretsImpl(AccountSecretsManager.kt:146)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:154)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[11:04:53 ERROR]:       at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:111)
[11:04:53 ERROR]:       at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:257)
[11:04:53 ERROR]:       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[11:04:53 ERROR]:       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[11:04:53 ERROR]:       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[11:04:53 ERROR]:       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[11:04:53 ERROR]:       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[11:04:53 ERROR]:       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[11:04:53 ERROR]: Caused by: java.util.jar.JarException: The JCE Provider file:/D:/waterfall/plugins/Phenyl/libs/mirai-core-all-2.10.0.jar is not signed.
[11:04:53 ERROR]:       at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
[11:04:53 ERROR]:       at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)
[11:04:53 ERROR]:       at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)
[11:04:53 ERROR]:       at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
[11:04:53 ERROR]:       at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)
[11:04:53 ERROR]:       at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)
[11:04:53 ERROR]:       at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128)
[11:04:53 ERROR]:       ... 29 more
